beacon_ax: 0.44
beacon_ay: 3.12
beacon_bx: 1.14
beacon_by: -0.08
beacon_cx: 1.84
beacon_cy: 3.12
predict_cov_a1: 1.5
predict_cov_a2: 2.5
predict_cov_a3: 1.5
predict_cov_a4: 2.5
update_cov_1: 0.01
update_cov_2: 0.01
update_cov_3: 0.02
mini_likelihood: -10000.0
mini_likelihood_update: 0.4
max_obstacle_distance: 0.5
